export const DEFAULT_HACKATHON_PARTICIPANTS = [
  {
    "id": "part-1",
    "sNo": 1,
    "teamSNo": 1,
    "fullName": "P. Jaya Pavan Kishore",
    "collegeName": "Godavari Global University",
    "teamName": "Aadhirta",
    "role": "Team Lead",
    "email": "penugondakishore2006@gmail.com",
    "phone": "+91 8074404321",
    "certId": "HACK26-001-L",
    "teamSize": 3
  },
  {
    "id": "part-2",
    "sNo": 2,
    "teamSNo": 1,
    "fullName": "P Revathi",
    "collegeName": "Godavari Global University",
    "teamName": "Aadhirta",
    "role": "Team Member",
    "email": "penugondarevathi2007@gmail.com",
    "phone": "+91 9515529965",
    "certId": "HACK26-001-M1",
    "teamSize": 3
  },
  {
    "id": "part-3",
    "sNo": 3,
    "teamSNo": 1,
    "fullName": "Padala Mounika Durga",
    "collegeName": "Godavari Global University",
    "teamName": "Aadhirta",
    "role": "Team Member",
    "email": "mounikadurgapadala19@gmail.com",
    "phone": "+91 9347761983",
    "certId": "HACK26-001-M2",
    "teamSize": 3
  },
  {
    "id": "part-4",
    "sNo": 4,
    "teamSNo": 2,
    "fullName": "Jyothi Pravallika Vasamsetti",
    "collegeName": "Godavari Global University",
    "teamName": "Achievers",
    "role": "Team Lead",
    "email": "jyothipravallika2813@gmail.com",
    "phone": "+91 9390663667",
    "certId": "HACK26-002-L",
    "teamSize": 2
  },
  {
    "id": "part-5",
    "sNo": 5,
    "teamSNo": 2,
    "fullName": "Sahithi Devi Adimulam",
    "collegeName": "Godavari Global University",
    "teamName": "Achievers",
    "role": "Team Member",
    "email": "deviasahithii@gmail.com",
    "phone": "+91 9704235608",
    "certId": "HACK26-002-M1",
    "teamSize": 2
  },
  {
    "id": "part-6",
    "sNo": 6,
    "teamSNo": 3,
    "fullName": "M.Puneeth",
    "collegeName": "Godavari Global University",
    "teamName": "Alpha",
    "role": "Team Lead",
    "email": "manellipuneeth48@gmail.com",
    "phone": "+91 9398481283",
    "certId": "HACK26-003-L",
    "teamSize": 3
  },
  {
    "id": "part-7",
    "sNo": 7,
    "teamSNo": 3,
    "fullName": "D.Sivaram",
    "collegeName": "Godavari Global University",
    "teamName": "Alpha",
    "role": "Team Member",
    "email": "sivaramd3177@gmail.com",
    "phone": "+91 7569918190",
    "certId": "HACK26-003-M1",
    "teamSize": 3
  },
  {
    "id": "part-8",
    "sNo": 8,
    "teamSNo": 3,
    "fullName": "K.Raja",
    "collegeName": "Godavari Global University",
    "teamName": "Alpha",
    "role": "Team Member",
    "email": "kopparthiraja52@gmail.com",
    "phone": "+91 7671820569",
    "certId": "HACK26-003-M2",
    "teamSize": 3
  },
  {
    "id": "part-9",
    "sNo": 9,
    "teamSNo": 4,
    "fullName": "SAI REDDY CHINTA",
    "collegeName": "Godavari Global University",
    "teamName": "Alt+f4",
    "role": "Team Lead",
    "email": "chintasaireddy2007@gmail.com",
    "phone": "+91 7780306061",
    "certId": "HACK26-004-L",
    "teamSize": 5
  },
  {
    "id": "part-10",
    "sNo": 10,
    "teamSNo": 4,
    "fullName": "GEESHMA TEJA KATTA",
    "collegeName": "Godavari Global University",
    "teamName": "Alt+f4",
    "role": "Team Member",
    "email": "geeshmateja@gmail.com",
    "phone": "+91 9491162153",
    "certId": "HACK26-004-M1",
    "teamSize": 5
  },
  {
    "id": "part-11",
    "sNo": 11,
    "teamSNo": 4,
    "fullName": "SHASHANK RAYUDU",
    "collegeName": "Godavari Global University",
    "teamName": "Alt+f4",
    "role": "Team Member",
    "email": "shashankhrayudu@gmail.com",
    "phone": "+91 8125471054",
    "certId": "HACK26-004-M2",
    "teamSize": 5
  },
  {
    "id": "part-12",
    "sNo": 12,
    "teamSNo": 4,
    "fullName": "YARRA SRIDEVI",
    "collegeName": "Godavari Global University",
    "teamName": "Alt+f4",
    "role": "Team Member",
    "email": "srideviyarra0@gmail.com",
    "phone": "+91 9030970268",
    "certId": "HACK26-004-M3",
    "teamSize": 5
  },
  {
    "id": "part-13",
    "sNo": 13,
    "teamSNo": 4,
    "fullName": "JAHNAVI PIDATALA",
    "collegeName": "Godavari Global University",
    "teamName": "Alt+f4",
    "role": "Team Member",
    "email": "pidatalajahnavi@gmail.com",
    "phone": "+91 7702270875",
    "certId": "HACK26-004-M4",
    "teamSize": 5
  },
  {
    "id": "part-14",
    "sNo": 14,
    "teamSNo": 5,
    "fullName": "Janapati UmaMahesh",
    "collegeName": "GIET Engineering College",
    "teamName": "Astra",
    "role": "Team Lead",
    "email": "maheshjanapati918@gmail.com",
    "phone": "+91 9182964244",
    "certId": "HACK26-005-L",
    "teamSize": 3
  },
  {
    "id": "part-15",
    "sNo": 15,
    "teamSNo": 5,
    "fullName": "Bharadwaj Anumula",
    "collegeName": "GIET Engineering College",
    "teamName": "Astra",
    "role": "Team Member",
    "email": "bharadwajanumula01@gmail.com",
    "phone": "+91 7671956435",
    "certId": "HACK26-005-M1",
    "teamSize": 3
  },
  {
    "id": "part-16",
    "sNo": 16,
    "teamSNo": 5,
    "fullName": "Kurru chandana satya sri",
    "collegeName": "GIET Engineering College",
    "teamName": "Astra",
    "role": "Team Member",
    "email": "kurruchandanasatyasri06@gmail.com",
    "phone": "+91 9701928149",
    "certId": "HACK26-005-M2",
    "teamSize": 3
  },
  {
    "id": "part-17",
    "sNo": 17,
    "teamSNo": 6,
    "fullName": "Manda Lohith",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "Astrax",
    "role": "Team Lead",
    "email": "lohith.manda24@sasi.ac.in",
    "phone": "+91 7993863439",
    "certId": "HACK26-006-L",
    "teamSize": 5
  },
  {
    "id": "part-18",
    "sNo": 18,
    "teamSNo": 6,
    "fullName": "Manoj",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "Astrax",
    "role": "Team Member",
    "email": "manoj.nujella24@sasi.ac.in",
    "phone": "+91 8179750199",
    "certId": "HACK26-006-M1",
    "teamSize": 5
  },
  {
    "id": "part-19",
    "sNo": 19,
    "teamSNo": 6,
    "fullName": "N Jayadeep",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "Astrax",
    "role": "Team Member",
    "email": "jayadeep.nidadavolu24@sasi.ac.in",
    "phone": "+91 9346119445",
    "certId": "HACK26-006-M2",
    "teamSize": 5
  },
  {
    "id": "part-20",
    "sNo": 20,
    "teamSNo": 6,
    "fullName": "P Poojitha",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "Astrax",
    "role": "Team Member",
    "email": "poojithapusula09@gmail.com",
    "phone": "+91 7702246648",
    "certId": "HACK26-006-M4",
    "teamSize": 5
  },
  {
    "id": "part-21",
    "sNo": 21,
    "teamSNo": 7,
    "fullName": "Palika ChandraSekhar",
    "collegeName": "Godavari Global University",
    "teamName": "Beyond Binary",
    "role": "Team Lead",
    "email": "chandrasekharpalika23@gmail.com",
    "phone": "+91 8328192203",
    "certId": "HACK26-007-L",
    "teamSize": 4
  },
  {
    "id": "part-22",
    "sNo": 22,
    "teamSNo": 7,
    "fullName": "Vogireddy vinee venkata lakshmi",
    "collegeName": "Godavari Global University",
    "teamName": "Beyond Binary",
    "role": "Team Member",
    "email": "vineesaivogireddy@gmail.com",
    "phone": "+91 9032550948",
    "certId": "HACK26-007-M1",
    "teamSize": 4
  },
  {
    "id": "part-23",
    "sNo": 23,
    "teamSNo": 7,
    "fullName": "Sankisa Jyoshika",
    "collegeName": "Godavari Global University",
    "teamName": "Beyond Binary",
    "role": "Team Member",
    "email": "jyoshika.sankisa@gmail.com",
    "phone": "+91 8978951633",
    "certId": "HACK26-007-M2",
    "teamSize": 4
  },
  {
    "id": "part-24",
    "sNo": 24,
    "teamSNo": 7,
    "fullName": "Vinjamuri Trylokya devi",
    "collegeName": "Godavari Global University",
    "teamName": "Beyond Binary",
    "role": "Team Member",
    "email": "thrilokyavinjamuri@gmail.com",
    "phone": "+91 6303842561",
    "certId": "HACK26-007-M3",
    "teamSize": 4
  },
  {
    "id": "part-25",
    "sNo": 25,
    "teamSNo": 8,
    "fullName": "Bhanu",
    "collegeName": "GIET Engineering College",
    "teamName": "Bhanu siri teja aswini",
    "role": "Team Lead",
    "email": "bhanusiritejaaswinik@gmail.com",
    "phone": "+91 9063015225",
    "certId": "HACK26-008-L",
    "teamSize": 1
  },
  {
    "id": "part-26",
    "sNo": 26,
    "teamSNo": 9,
    "fullName": "Tharunya Yaladandi",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "Code  Y",
    "role": "Team Lead",
    "email": "yaladanditharunya@gmail.com",
    "phone": "+91 6302560879",
    "certId": "HACK26-009-L",
    "teamSize": 3
  },
  {
    "id": "part-27",
    "sNo": 27,
    "teamSNo": 9,
    "fullName": "Renuka  Amalapurapu",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "Code  Y",
    "role": "Team Member",
    "email": "renukadeviamalapurapu@gmail.com",
    "phone": "+91 9052940966",
    "certId": "HACK26-009-M1",
    "teamSize": 3
  },
  {
    "id": "part-28",
    "sNo": 28,
    "teamSNo": 9,
    "fullName": "Gabu Mahalakshmi Ganga Bhavani",
    "collegeName": "Godavari Global University",
    "teamName": "Code  Y",
    "role": "Team Member",
    "email": "gabu.mlgbhavani06@gmail.com",
    "phone": "+91 63045 02230",
    "certId": "HACK26-009-M2",
    "teamSize": 3
  },
  {
    "id": "part-29",
    "sNo": 29,
    "teamSNo": 10,
    "fullName": "Pradeep Meesala",
    "collegeName": "Godavari Global University",
    "teamName": "code avenger",
    "role": "Team Lead",
    "email": "pradeepmeesala12@gmail.com",
    "phone": "+91 9182258189",
    "certId": "HACK26-010-L",
    "teamSize": 1
  },
  {
    "id": "part-30",
    "sNo": 30,
    "teamSNo": 11,
    "fullName": "S.Rishitha",
    "collegeName": "Godavari Global University",
    "teamName": "Code stomers",
    "role": "Team Lead",
    "email": "srisatyarishitha@gmail.com",
    "phone": "+91 9493761499",
    "certId": "HACK26-011-L",
    "teamSize": 3
  },
  {
    "id": "part-31",
    "sNo": 31,
    "teamSNo": 11,
    "fullName": "P.Hadhasa",
    "collegeName": "Godavari Global University",
    "teamName": "Code stomers",
    "role": "Team Member",
    "email": "hadhasapilli@gmail.com",
    "phone": "+91 6303076960",
    "certId": "HACK26-011-M1",
    "teamSize": 3
  },
  {
    "id": "part-32",
    "sNo": 32,
    "teamSNo": 11,
    "fullName": "P.Sridevi",
    "collegeName": "Godavari Global University",
    "teamName": "Code stomers",
    "role": "Team Member",
    "email": "sridevipalla106@gmail.com",
    "phone": "+91 8978507977",
    "certId": "HACK26-011-M2",
    "teamSize": 3
  },
  {
    "id": "part-33",
    "sNo": 33,
    "teamSNo": 12,
    "fullName": "Kavya Sri",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "Codhex",
    "role": "Team Lead",
    "email": "dharakavya01@gmail.com",
    "phone": "+91 6304936968",
    "certId": "HACK26-012-L",
    "teamSize": 4
  },
  {
    "id": "part-34",
    "sNo": 34,
    "teamSNo": 12,
    "fullName": "K.Avinash",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "Codhex",
    "role": "Team Member",
    "email": "avinashkodamanchili54@gmail.com",
    "phone": "+91 8688524528",
    "certId": "HACK26-012-M2",
    "teamSize": 4
  },
  {
    "id": "part-35",
    "sNo": 35,
    "teamSNo": 12,
    "fullName": "B.Dhanaraju",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "Codhex",
    "role": "Team Member",
    "email": "dhanarajubokka118@gmail.com",
    "phone": "+91 7989884148",
    "certId": "HACK26-012-M3",
    "teamSize": 4
  },
  {
    "id": "part-36",
    "sNo": 36,
    "teamSNo": 13,
    "fullName": "Maha Lakshmi",
    "collegeName": "GIET Engineering College",
    "teamName": "CSE -GIET",
    "role": "Team Lead",
    "email": "yallamahalalakshmi2106@gmail.com",
    "phone": "+91 9177215556",
    "certId": "HACK26-013-L",
    "teamSize": 4
  },
  {
    "id": "part-37",
    "sNo": 37,
    "teamSNo": 13,
    "fullName": "Jyothsna Arangi",
    "collegeName": "GIET Engineering College",
    "teamName": "CSE -GIET",
    "role": "Team Member",
    "email": "jyosthnaarangi816@gmail.com",
    "phone": "+91 9959625037",
    "certId": "HACK26-013-M1",
    "teamSize": 4
  },
  {
    "id": "part-38",
    "sNo": 38,
    "teamSNo": 13,
    "fullName": "Bonu kishore",
    "collegeName": "GIET Engineering College",
    "teamName": "CSE -GIET",
    "role": "Team Member",
    "email": "bonukishore362@gmail.com",
    "phone": "+91 7995928226",
    "certId": "HACK26-013-M2",
    "teamSize": 4
  },
  {
    "id": "part-39",
    "sNo": 39,
    "teamSNo": 13,
    "fullName": "Lanka Vinay vamsi",
    "collegeName": "GIET Engineering College",
    "teamName": "CSE -GIET",
    "role": "Team Member",
    "email": "lankavinayvamsi@gmail.com",
    "phone": "+91 9390378365",
    "certId": "HACK26-013-M3",
    "teamSize": 4
  },
  {
    "id": "part-40",
    "sNo": 40,
    "teamSNo": 14,
    "fullName": "Gollapalli Krishna Sahith",
    "collegeName": "Godavari Global University",
    "teamName": "Dev-28",
    "role": "Team Lead",
    "email": "sahithgollapalli@gmail.com",
    "phone": "+91 7207260327",
    "certId": "HACK26-014-L",
    "teamSize": 4
  },
  {
    "id": "part-41",
    "sNo": 41,
    "teamSNo": 14,
    "fullName": "Geddada Jitendra",
    "collegeName": "Godavari Global University",
    "teamName": "Dev-28",
    "role": "Team Member",
    "email": "jitendra178842005@gmail.com",
    "phone": "+91 9502919217",
    "certId": "HACK26-014-M1",
    "teamSize": 4
  },
  {
    "id": "part-42",
    "sNo": 42,
    "teamSNo": 14,
    "fullName": "Narayana gari snehith kumar",
    "collegeName": "Godavari Global University",
    "teamName": "Dev-28",
    "role": "Team Member",
    "email": "snehithkunar14@gmail.com",
    "phone": "+91 8309851311",
    "certId": "HACK26-014-M2",
    "teamSize": 4
  },
  {
    "id": "part-43",
    "sNo": 43,
    "teamSNo": 14,
    "fullName": "Mylapalli Bala Raju",
    "collegeName": "Godavari Global University",
    "teamName": "Dev-28",
    "role": "Team Member",
    "email": "mylapalliraju438@gmail.com",
    "phone": "+91 9989631303",
    "certId": "HACK26-014-M3",
    "teamSize": 4
  },
  {
    "id": "part-44",
    "sNo": 44,
    "teamSNo": 15,
    "fullName": "Gowroju SriLakshmi Prasanna",
    "collegeName": "GIET Engineering College",
    "teamName": "DualStack",
    "role": "Team Lead",
    "email": "sri2006prasanna@gmail.com",
    "phone": "+91 8639301438",
    "certId": "HACK26-015-L",
    "teamSize": 2
  },
  {
    "id": "part-45",
    "sNo": 45,
    "teamSNo": 15,
    "fullName": "Kantaspurthi Sri Girija Surya Pravalli",
    "collegeName": "GIET Engineering College",
    "teamName": "DualStack",
    "role": "Team Member",
    "email": "pravallikantaspurthi@gmail.com",
    "phone": "+91 9346836153",
    "certId": "HACK26-015-M1",
    "teamSize": 2
  },
  {
    "id": "part-46",
    "sNo": 46,
    "teamSNo": 16,
    "fullName": "Challa Kalyan",
    "collegeName": "Godavari Global University",
    "teamName": "Elite",
    "role": "Team Lead",
    "email": "challakalyan1729@gmail.com",
    "phone": "+91 9030631653",
    "certId": "HACK26-016-L",
    "teamSize": 2
  },
  {
    "id": "part-47",
    "sNo": 47,
    "teamSNo": 17,
    "fullName": "Anukolu Anand Reddy",
    "collegeName": "Godavari Global University",
    "teamName": "GenZaura",
    "role": "Team Lead",
    "email": "anandreddyanukolu@gmail.com",
    "phone": "+91 7075735324",
    "certId": "HACK26-017-L",
    "teamSize": 4
  },
  {
    "id": "part-48",
    "sNo": 48,
    "teamSNo": 17,
    "fullName": "Praneeth Kumar",
    "collegeName": "Godavari Global University",
    "teamName": "GenZaura",
    "role": "Team Member",
    "email": "praneethkumarsindhe@gmail.com",
    "phone": "+91 9908678503",
    "certId": "HACK26-017-M1",
    "teamSize": 4
  },
  {
    "id": "part-49",
    "sNo": 49,
    "teamSNo": 17,
    "fullName": "Aditya venkata sai",
    "collegeName": "Godavari Global University",
    "teamName": "GenZaura",
    "role": "Team Member",
    "email": "adityakandiboina@gmail.com",
    "phone": "+91 9652567753",
    "certId": "HACK26-017-M2",
    "teamSize": 4
  },
  {
    "id": "part-50",
    "sNo": 50,
    "teamSNo": 17,
    "fullName": "Jagadeesh Babu",
    "collegeName": "Godavari Global University",
    "teamName": "GenZaura",
    "role": "Team Member",
    "email": "jagadeeshbabuyandra7@gmail.com",
    "phone": "+91 9281446752",
    "certId": "HACK26-017-M3",
    "teamSize": 4
  },
  {
    "id": "part-51",
    "sNo": 51,
    "teamSNo": 18,
    "fullName": "Koppisetty Dhana venkata vishnu vigneswar",
    "collegeName": "Godavari Global University",
    "teamName": "Ggu vipers",
    "role": "Team Lead",
    "email": "vara14008@gmail.com",
    "phone": "+91 9133940189",
    "certId": "HACK26-018-L",
    "teamSize": 3
  },
  {
    "id": "part-52",
    "sNo": 52,
    "teamSNo": 18,
    "fullName": "Prathviraj singh ranawat",
    "collegeName": "Godavari Global University",
    "teamName": "Ggu vipers",
    "role": "Team Member",
    "email": "ranawatprithviraj4@gmail.com",
    "phone": "+91 9660624766",
    "certId": "HACK26-018-M1",
    "teamSize": 3
  },
  {
    "id": "part-53",
    "sNo": 53,
    "teamSNo": 18,
    "fullName": "Velugubantla Abhiram",
    "collegeName": "Godavari Global University",
    "teamName": "Ggu vipers",
    "role": "Team Member",
    "email": "abhiramvelugubantla6@gamil.com",
    "phone": "+91 7981539792",
    "certId": "HACK26-018-M2",
    "teamSize": 3
  },
  {
    "id": "part-54",
    "sNo": 54,
    "teamSNo": 19,
    "fullName": "Bokka Bala Nagendra Ganesh",
    "collegeName": "Godavari Global University",
    "teamName": "GNANEX",
    "role": "Team Lead",
    "email": "nagendra.07.5486@gmail.com",
    "phone": "+91 6304502230",
    "certId": "HACK26-019-L",
    "teamSize": 5
  },
  {
    "id": "part-55",
    "sNo": 55,
    "teamSNo": 19,
    "fullName": "Gandham Rohith Venkata Kumar",
    "collegeName": "Godavari Global University",
    "teamName": "GNANEX",
    "role": "Team Member",
    "email": "gandhamrohithvenkatakumar@gmail.com",
    "phone": "+91 9666173499",
    "certId": "HACK26-019-M2",
    "teamSize": 5
  },
  {
    "id": "part-56",
    "sNo": 56,
    "teamSNo": 19,
    "fullName": "Dudekula Sai Teja",
    "collegeName": "Godavari Global University",
    "teamName": "GNANEX",
    "role": "Team Member",
    "email": "saitejadudekula0@gmail.com",
    "phone": "+91 6302007089",
    "certId": "HACK26-019-M3",
    "teamSize": 5
  },
  {
    "id": "part-57",
    "sNo": 57,
    "teamSNo": 19,
    "fullName": "Menavath Venkata Mahesh Naik",
    "collegeName": "Godavari Global University",
    "teamName": "GNANEX",
    "role": "Team Member",
    "email": "maheshnaikn977@gmail.com",
    "phone": "+91 6303006752",
    "certId": "HACK26-019-M4",
    "teamSize": 5
  },
  {
    "id": "part-58",
    "sNo": 58,
    "teamSNo": 20,
    "fullName": "Gudala Abhinay",
    "collegeName": "GIET Engineering College",
    "teamName": "Gudala Abhinay",
    "role": "Team Lead",
    "email": "abhinaygoud49@gmail.com",
    "phone": "+91 9390952712",
    "certId": "HACK26-020-L",
    "teamSize": 4
  },
  {
    "id": "part-59",
    "sNo": 59,
    "teamSNo": 20,
    "fullName": "Gundabathina Anand",
    "collegeName": "GIET Engineering College",
    "teamName": "Gudala Abhinay",
    "role": "Team Member",
    "email": "anandgundabathina@gmail.com",
    "phone": "+91 8125804266",
    "certId": "HACK26-020-M1",
    "teamSize": 4
  },
  {
    "id": "part-60",
    "sNo": 60,
    "teamSNo": 20,
    "fullName": "Nerusu Gnana Deepa",
    "collegeName": "GIET Engineering College",
    "teamName": "Gudala Abhinay",
    "role": "Team Member",
    "email": "nerusugnanadeepa@gmail.com",
    "phone": "+91 8019784277",
    "certId": "HACK26-020-M2",
    "teamSize": 4
  },
  {
    "id": "part-61",
    "sNo": 61,
    "teamSNo": 20,
    "fullName": "Epuri  John Wesley",
    "collegeName": "GIET Engineering College",
    "teamName": "Gudala Abhinay",
    "role": "Team Member",
    "email": "jw.johnwesly5@gmail.cpm",
    "phone": "+91 9347688424",
    "certId": "HACK26-020-M3",
    "teamSize": 4
  },
  {
    "id": "part-62",
    "sNo": 62,
    "teamSNo": 21,
    "fullName": "Mohamed Musraf",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "IIITIANS",
    "role": "Team Lead",
    "email": "musrafmohamed75@gmail.com",
    "phone": "+91 8072301941",
    "certId": "HACK26-021-L",
    "teamSize": 4
  },
  {
    "id": "part-63",
    "sNo": 63,
    "teamSNo": 21,
    "fullName": "Mohammad Riyaz Baba",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "IIITIANS",
    "role": "Team Member",
    "email": "rmd63511@gmail.com",
    "phone": "+91 9346044784",
    "certId": "HACK26-021-M1",
    "teamSize": 4
  },
  {
    "id": "part-64",
    "sNo": 64,
    "teamSNo": 21,
    "fullName": "Sundarapu Tharun",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "IIITIANS",
    "role": "Team Member",
    "email": "s220050@rguktsklm.ac.in",
    "phone": "+91 9000950368",
    "certId": "HACK26-021-M2",
    "teamSize": 4
  },
  {
    "id": "part-65",
    "sNo": 65,
    "teamSNo": 21,
    "fullName": "Veturi sri ram",
    "collegeName": "RGUKT Srikakulam",
    "teamName": "IIITIANS",
    "role": "Team Member",
    "email": "veturisriramkumar@gmail.com",
    "phone": "+91 6301050585",
    "certId": "HACK26-021-M3",
    "teamSize": 4
  },
  {
    "id": "part-66",
    "sNo": 66,
    "teamSNo": 22,
    "fullName": "Kapurapu Yaswanth Reddy",
    "collegeName": "Godavari Global University",
    "teamName": "InnoGen",
    "role": "Team Lead",
    "email": "kapurapuyaswanthreddy@gmail.com",
    "phone": "+91 9392722382",
    "certId": "HACK26-022-L",
    "teamSize": 3
  },
  {
    "id": "part-67",
    "sNo": 67,
    "teamSNo": 22,
    "fullName": "Surya Raja Mandapalli",
    "collegeName": "Godavari Global University",
    "teamName": "InnoGen",
    "role": "Team Member",
    "email": "suryarajamandapalli@gmail.com",
    "phone": "+91 7331102624",
    "certId": "HACK26-022-M1",
    "teamSize": 3
  },
  {
    "id": "part-68",
    "sNo": 68,
    "teamSNo": 22,
    "fullName": "Mallikarjun Reddy",
    "collegeName": "Godavari Global University",
    "teamName": "InnoGen",
    "role": "Team Member",
    "email": "mkreddy1117@gmail.com",
    "phone": "+91 7095328480",
    "certId": "HACK26-022-M2",
    "teamSize": 3
  },
  {
    "id": "part-69",
    "sNo": 69,
    "teamSNo": 23,
    "fullName": "P. karthikeya",
    "collegeName": "Godavari Global University",
    "teamName": "Innov8 squad",
    "role": "Team Lead",
    "email": "pkarthikeya807@gmail.com",
    "phone": "+91 8074585055",
    "certId": "HACK26-023-L",
    "teamSize": 4
  },
  {
    "id": "part-70",
    "sNo": 70,
    "teamSNo": 23,
    "fullName": "K.Sharath",
    "collegeName": "Godavari Global University",
    "teamName": "Innov8 squad",
    "role": "Team Member",
    "email": "sharathkodumuru@gmail.com",
    "phone": "+91 9154255420",
    "certId": "HACK26-023-M1",
    "teamSize": 4
  },
  {
    "id": "part-71",
    "sNo": 71,
    "teamSNo": 23,
    "fullName": "SK.Ayesha Begum",
    "collegeName": "Godavari Global University",
    "teamName": "Innov8 squad",
    "role": "Team Member",
    "email": "skayesha0606@gmail.com",
    "phone": "+91 9618441292",
    "certId": "HACK26-023-M2",
    "teamSize": 4
  },
  {
    "id": "part-72",
    "sNo": 72,
    "teamSNo": 23,
    "fullName": "M.Thananya",
    "collegeName": "Godavari Global University",
    "teamName": "Innov8 squad",
    "role": "Team Member",
    "email": "mekalathanaya06@gmail.com",
    "phone": "+91 8143281649",
    "certId": "HACK26-023-M3",
    "teamSize": 4
  },
  {
    "id": "part-73",
    "sNo": 73,
    "teamSNo": 24,
    "fullName": "Koppisetty Sathvika Devi",
    "collegeName": "Godavari Global University",
    "teamName": "INNOVATION CREW",
    "role": "Team Lead",
    "email": "koppisettysathvika666@gmail.com",
    "phone": "+91 7989296386",
    "certId": "HACK26-024-L",
    "teamSize": 4
  },
  {
    "id": "part-74",
    "sNo": 74,
    "teamSNo": 24,
    "fullName": "Dongara Satya Prasad",
    "collegeName": "Godavari Global University",
    "teamName": "INNOVATION CREW",
    "role": "Team Member",
    "email": "dongaraprasad@gmail.com",
    "phone": "+91 7287909451",
    "certId": "HACK26-024-M1",
    "teamSize": 4
  },
  {
    "id": "part-75",
    "sNo": 75,
    "teamSNo": 24,
    "fullName": "Bongarala Jyoshna Gowri",
    "collegeName": "Godavari Global University",
    "teamName": "INNOVATION CREW",
    "role": "Team Member",
    "email": "jyoshnagowri05@gmail.com",
    "phone": "+91 9182078451",
    "certId": "HACK26-024-M2",
    "teamSize": 4
  },
  {
    "id": "part-76",
    "sNo": 76,
    "teamSNo": 24,
    "fullName": "Adapa Karthikeya sai",
    "collegeName": "Godavari Global University",
    "teamName": "INNOVATION CREW",
    "role": "Team Member",
    "email": "karthikeyasai61@gmail.com",
    "phone": "+91 9246668777",
    "certId": "HACK26-024-M3",
    "teamSize": 4
  },
  {
    "id": "part-77",
    "sNo": 77,
    "teamSNo": 25,
    "fullName": "VARIKUTI PUSHPANJALI",
    "collegeName": "Godavari Global University",
    "teamName": "Innovexa",
    "role": "Team Lead",
    "email": "varikutipushpanjalinaidu@gmail.com",
    "phone": "+91 9381205770",
    "certId": "HACK26-025-L",
    "teamSize": 4
  },
  {
    "id": "part-78",
    "sNo": 78,
    "teamSNo": 25,
    "fullName": "Santhanmai jaladi",
    "collegeName": "Godavari Global University",
    "teamName": "Innovexa",
    "role": "Team Member",
    "email": "santhujaladi@gmail.com",
    "phone": "+91 7680855893",
    "certId": "HACK26-025-M1",
    "teamSize": 4
  },
  {
    "id": "part-79",
    "sNo": 79,
    "teamSNo": 25,
    "fullName": "Pothuraju tulasi venkata gopi Krishna",
    "collegeName": "Godavari Global University",
    "teamName": "Innovexa",
    "role": "Team Member",
    "email": "pothurajugopi8@gmail.com",
    "phone": "+91 9346486273",
    "certId": "HACK26-025-M2",
    "teamSize": 4
  },
  {
    "id": "part-80",
    "sNo": 80,
    "teamSNo": 25,
    "fullName": "KORADA MANIKANTA",
    "collegeName": "Godavari Global University",
    "teamName": "Innovexa",
    "role": "Team Member",
    "email": "manikantakorda939@gmail.com",
    "phone": "+91 9381637430",
    "certId": "HACK26-025-M3",
    "teamSize": 4
  },
  {
    "id": "part-81",
    "sNo": 81,
    "teamSNo": 26,
    "fullName": "Alisha Shaik",
    "collegeName": "Pragati Engineering College / University",
    "teamName": "Innovexa",
    "role": "Team Lead",
    "email": "alishashiak1606@gmail.com",
    "phone": "+91 8019711713",
    "certId": "HACK26-026-L",
    "teamSize": 5
  },
  {
    "id": "part-82",
    "sNo": 82,
    "teamSNo": 26,
    "fullName": "A Rohit vijay",
    "collegeName": "Pragati Engineering College / University",
    "teamName": "Innovexa",
    "role": "Team Member",
    "email": "rohitvijayapapa2006@gmail.com",
    "phone": "+91 9133755914",
    "certId": "HACK26-026-M2",
    "teamSize": 5
  },
  {
    "id": "part-83",
    "sNo": 83,
    "teamSNo": 26,
    "fullName": "Shauk Rijwana",
    "collegeName": "Pragati Engineering College / University",
    "teamName": "Innovexa",
    "role": "Team Member",
    "email": "rijwanashaik1229@gmail.com",
    "phone": "+91 9573743439",
    "certId": "HACK26-026-M3",
    "teamSize": 5
  },
  {
    "id": "part-84",
    "sNo": 84,
    "teamSNo": 26,
    "fullName": "Bogireddy Aparna",
    "collegeName": "Pragati Engineering College / University",
    "teamName": "Innovexa",
    "role": "Team Member",
    "email": "aparnabogireddy17@gmail.com",
    "phone": "+91 9640620956",
    "certId": "HACK26-026-M4",
    "teamSize": 5
  },
  {
    "id": "part-85",
    "sNo": 85,
    "teamSNo": 27,
    "fullName": "Kesavarapu Surya Ishwarya",
    "collegeName": "Godavari Global University",
    "teamName": "Ishu and team",
    "role": "Team Lead",
    "email": "ishukesavarapu29@gmail.com",
    "phone": "+91 6300824026",
    "certId": "HACK26-027-L",
    "teamSize": 4
  },
  {
    "id": "part-86",
    "sNo": 86,
    "teamSNo": 27,
    "fullName": "Medisetty Tejasri",
    "collegeName": "Godavari Global University",
    "teamName": "Ishu and team",
    "role": "Team Member",
    "email": "medisettytejasri@gmail.com",
    "phone": "+91 9848254447",
    "certId": "HACK26-027-M1",
    "teamSize": 4
  },
  {
    "id": "part-87",
    "sNo": 87,
    "teamSNo": 27,
    "fullName": "Kommireddy Megha Sanjana",
    "collegeName": "Godavari Global University",
    "teamName": "Ishu and team",
    "role": "Team Member",
    "email": "kommireddymegasanjana@gmail.com",
    "phone": "+91 8309034447",
    "certId": "HACK26-027-M2",
    "teamSize": 4
  },
  {
    "id": "part-88",
    "sNo": 88,
    "teamSNo": 27,
    "fullName": "Bathula Bala sireesha",
    "collegeName": "Godavari Global University",
    "teamName": "Ishu and team",
    "role": "Team Member",
    "email": "bathulasireesha131@gmail.com",
    "phone": "+91 8106110078",
    "certId": "HACK26-027-M3",
    "teamSize": 4
  },
  {
    "id": "part-89",
    "sNo": 89,
    "teamSNo": 28,
    "fullName": "Neo Seelam",
    "collegeName": "Godavari Global University",
    "teamName": "LARP",
    "role": "Team Lead",
    "email": "nezareeen@gmail.com",
    "phone": "+91 9959888429",
    "certId": "HACK26-028-L",
    "teamSize": 2
  },
  {
    "id": "part-90",
    "sNo": 90,
    "teamSNo": 28,
    "fullName": "Madhu Kiran Inaparthi",
    "collegeName": "Godavari Global University",
    "teamName": "LARP",
    "role": "Team Member",
    "email": "madhukiraninaparthi@gmail.com",
    "phone": "+91 8141416194",
    "certId": "HACK26-028-M1",
    "teamSize": 2
  },
  {
    "id": "part-91",
    "sNo": 91,
    "teamSNo": 29,
    "fullName": "R Navya Teja Sri",
    "collegeName": "Godavari Global University",
    "teamName": "Navya",
    "role": "Team Lead",
    "email": "gamyasrirelangi1@gmail.com",
    "phone": "+91 9490588879",
    "certId": "HACK26-029-L",
    "teamSize": 1
  },
  {
    "id": "part-92",
    "sNo": 92,
    "teamSNo": 30,
    "fullName": "Somanchi Kameswari Sindhuja",
    "collegeName": "Godavari Global University",
    "teamName": "Nerdy",
    "role": "Team Lead",
    "email": "sindhuja.somanchi2025@gmail.com",
    "phone": "+91 9391230185",
    "certId": "HACK26-030-L",
    "teamSize": 4
  },
  {
    "id": "part-93",
    "sNo": 93,
    "teamSNo": 30,
    "fullName": "Meher Siva Ram Sorampudi",
    "collegeName": "Godavari Global University",
    "teamName": "Nerdy",
    "role": "Team Member",
    "email": "smsram001@gmail.com",
    "phone": "+91 7995302506",
    "certId": "HACK26-030-M1",
    "teamSize": 4
  },
  {
    "id": "part-94",
    "sNo": 94,
    "teamSNo": 30,
    "fullName": "Akhil Tangila",
    "collegeName": "Godavari Global University",
    "teamName": "Nerdy",
    "role": "Team Member",
    "email": "akhiltangila131@gmail.com",
    "phone": "+91 8121763248",
    "certId": "HACK26-030-M2",
    "teamSize": 4
  },
  {
    "id": "part-95",
    "sNo": 95,
    "teamSNo": 31,
    "fullName": "Jaswanth Sai",
    "collegeName": "Godavari Global University",
    "teamName": "Neural nomads",
    "role": "Team Lead",
    "email": "jaswanthsai9696@gmail.com",
    "phone": "+91 9494847250",
    "certId": "HACK26-031-L",
    "teamSize": 5
  },
  {
    "id": "part-96",
    "sNo": 96,
    "teamSNo": 31,
    "fullName": "Karri pujitha",
    "collegeName": "Godavari Global University",
    "teamName": "Neural nomads",
    "role": "Team Member",
    "email": "pujithakarri16@gmail.com",
    "phone": "+91 6303754170",
    "certId": "HACK26-031-M1",
    "teamSize": 5
  },
  {
    "id": "part-97",
    "sNo": 97,
    "teamSNo": 31,
    "fullName": "Illa  Nikitha  harini",
    "collegeName": "Godavari Global University",
    "teamName": "Neural nomads",
    "role": "Team Member",
    "email": "hariniila123@gmail.com",
    "phone": "+91 8074058949",
    "certId": "HACK26-031-M2",
    "teamSize": 5
  },
  {
    "id": "part-98",
    "sNo": 98,
    "teamSNo": 31,
    "fullName": "Sayyed  Mouzama Amrin",
    "collegeName": "Godavari Global University",
    "teamName": "Neural nomads",
    "role": "Team Member",
    "email": "amrinsayyed2007@gmail.com",
    "phone": "+91 9182718104",
    "certId": "HACK26-031-M3",
    "teamSize": 5
  },
  {
    "id": "part-99",
    "sNo": 99,
    "teamSNo": 31,
    "fullName": "Undamatla Vijaya durga",
    "collegeName": "Godavari Global University",
    "teamName": "Neural nomads",
    "role": "Team Member",
    "email": "undamatlavijayadurga@gmail.com",
    "phone": "+91 7842380903",
    "certId": "HACK26-031-M4",
    "teamSize": 5
  },
  {
    "id": "part-100",
    "sNo": 100,
    "teamSNo": 32,
    "fullName": "Tej Raghuveer",
    "collegeName": "Godavari Global University",
    "teamName": "Potato team",
    "role": "Team Lead",
    "email": "tejmotipalli@gmail.com",
    "phone": "+91 9553322890",
    "certId": "HACK26-032-L",
    "teamSize": 2
  },
  {
    "id": "part-101",
    "sNo": 101,
    "teamSNo": 32,
    "fullName": "Varshith",
    "collegeName": "Godavari Global University",
    "teamName": "Potato team",
    "role": "Team Member",
    "email": "varshith5006@gmail.com",
    "phone": "+91 6305333182",
    "certId": "HACK26-032-M1",
    "teamSize": 2
  },
  {
    "id": "part-102",
    "sNo": 102,
    "teamSNo": 33,
    "fullName": "Indugu BhanuPrakash",
    "collegeName": "Godavari Global University",
    "teamName": "Raise again",
    "role": "Team Lead",
    "email": "indugugopalsai123@gmail.com",
    "phone": "+91 9963079610",
    "certId": "HACK26-033-L",
    "teamSize": 4
  },
  {
    "id": "part-103",
    "sNo": 103,
    "teamSNo": 33,
    "fullName": "Jami Dola Suraj Abhishek",
    "collegeName": "Godavari Global University",
    "teamName": "Raise again",
    "role": "Team Member",
    "email": "surajabhishek82667@gmail.com",
    "phone": "+91 8919982667",
    "certId": "HACK26-033-M1",
    "teamSize": 4
  },
  {
    "id": "part-104",
    "sNo": 104,
    "teamSNo": 33,
    "fullName": "Kosanam Sai charan",
    "collegeName": "Godavari Global University",
    "teamName": "Raise again",
    "role": "Team Member",
    "email": "kosanamsaicharan29@gmail.com",
    "phone": "+91 8309751500",
    "certId": "HACK26-033-M3",
    "teamSize": 4
  },
  {
    "id": "part-105",
    "sNo": 105,
    "teamSNo": 34,
    "fullName": "V KRISHNA KOUSHIK",
    "collegeName": "Godavari Global University",
    "teamName": "Rudra",
    "role": "Team Lead",
    "email": "krishnakoushik297@gmail.com",
    "phone": "+91 9515578035",
    "certId": "HACK26-034-L",
    "teamSize": 4
  },
  {
    "id": "part-106",
    "sNo": 106,
    "teamSNo": 34,
    "fullName": "K Chandra Neel Reddy",
    "collegeName": "Godavari Global University",
    "teamName": "Rudra",
    "role": "Team Member",
    "email": "bannireddy714@gmail.com",
    "phone": "+91 8978385628",
    "certId": "HACK26-034-M2",
    "teamSize": 4
  },
  {
    "id": "part-107",
    "sNo": 107,
    "teamSNo": 34,
    "fullName": "K.gireeshroyal",
    "collegeName": "Godavari Global University",
    "teamName": "Rudra",
    "role": "Team Member",
    "email": "girreeshroyalkunapareddy@gmail.com",
    "phone": "+91 9700551775",
    "certId": "HACK26-034-M3",
    "teamSize": 4
  },
  {
    "id": "part-108",
    "sNo": 108,
    "teamSNo": 35,
    "fullName": "SHESHETTI PAVAN KUMAR SWAMY",
    "collegeName": "GIET Engineering College",
    "teamName": "Sample",
    "role": "Team Lead",
    "email": "shesettipavankumarswamy@gmail.com",
    "phone": "+91 8639122823",
    "certId": "HACK26-035-L",
    "teamSize": 2
  },
  {
    "id": "part-109",
    "sNo": 109,
    "teamSNo": 36,
    "fullName": "POKALA SATYA KARTHIK",
    "collegeName": "GODAVARI  GLOBAL UNIVERSITY",
    "teamName": "Savini duo",
    "role": "Team Lead",
    "email": "satyakarthikpokala@gmail.com",
    "phone": "+91 9490897297",
    "certId": "HACK26-036-L",
    "teamSize": 2
  },
  {
    "id": "part-110",
    "sNo": 110,
    "teamSNo": 36,
    "fullName": "BEESETTY VENKATA SASIDHAR",
    "collegeName": "GODAVARI  GLOBAL UNIVERSITY",
    "teamName": "Savini duo",
    "role": "Team Member",
    "email": "sasidhar1078@gmail.com",
    "phone": "+91 7013621750",
    "certId": "HACK26-036-M1",
    "teamSize": 2
  },
  {
    "id": "part-111",
    "sNo": 111,
    "teamSNo": 37,
    "fullName": "Eunice Anusha K",
    "collegeName": "Godavari Global University",
    "teamName": "Solution sprints",
    "role": "Team Lead",
    "email": "sweetyeunice27@gmail.com",
    "phone": "+91 6303720766",
    "certId": "HACK26-037-L",
    "teamSize": 4
  },
  {
    "id": "part-112",
    "sNo": 112,
    "teamSNo": 37,
    "fullName": "Harshita A",
    "collegeName": "Godavari Global University",
    "teamName": "Solution sprints",
    "role": "Team Member",
    "email": "harshitaalamuri@gmail.com",
    "phone": "+91 8522827302",
    "certId": "HACK26-037-M1",
    "teamSize": 4
  },
  {
    "id": "part-113",
    "sNo": 113,
    "teamSNo": 37,
    "fullName": "B.S.V.Jaswanth Tej",
    "collegeName": "Godavari Global University",
    "teamName": "Solution sprints",
    "role": "Team Member",
    "email": "jaswanathbandaru73@gmail.com",
    "phone": "+91 9951087045",
    "certId": "HACK26-037-M2",
    "teamSize": 4
  },
  {
    "id": "part-114",
    "sNo": 114,
    "teamSNo": 37,
    "fullName": "G.Karuna sagar",
    "collegeName": "Godavari Global University",
    "teamName": "Solution sprints",
    "role": "Team Member",
    "email": "pavankaruna9@gmail.com",
    "phone": "+91 8247727295",
    "certId": "HACK26-037-M3",
    "teamSize": 4
  },
  {
    "id": "part-115",
    "sNo": 115,
    "teamSNo": 38,
    "fullName": "Oggu Bhanusasitha",
    "collegeName": "Godavari Global University",
    "teamName": "Team Astra",
    "role": "Team Lead",
    "email": "bhanusasithaoggu@gmail.com",
    "phone": "+91 9704585919",
    "certId": "HACK26-038-L",
    "teamSize": 2
  },
  {
    "id": "part-116",
    "sNo": 116,
    "teamSNo": 38,
    "fullName": "Patchava Likhitha",
    "collegeName": "Godavari Global University",
    "teamName": "Team Astra",
    "role": "Team Member",
    "email": "likhithapatchava@gmail.com",
    "phone": "+91 6303054058",
    "certId": "HACK26-038-M1",
    "teamSize": 2
  },
  {
    "id": "part-117",
    "sNo": 117,
    "teamSNo": 39,
    "fullName": "P. Venkata Siva Ajay",
    "collegeName": "GIET Engineering College",
    "teamName": "Team E",
    "role": "Team Lead",
    "email": "pvenkatasivaajay@gmail.com",
    "phone": "+91 7013112390",
    "certId": "HACK26-039-L",
    "teamSize": 3
  },
  {
    "id": "part-118",
    "sNo": 118,
    "teamSNo": 39,
    "fullName": "R. Abhilash",
    "collegeName": "GIET Engineering College",
    "teamName": "Team E",
    "role": "Team Member",
    "email": "rajapantulaabhilash003@gmail.com",
    "phone": "+91 9390064344",
    "certId": "HACK26-039-M1",
    "teamSize": 3
  },
  {
    "id": "part-119",
    "sNo": 119,
    "teamSNo": 39,
    "fullName": "D. Deviprasad",
    "collegeName": "GIET Engineering College",
    "teamName": "Team E",
    "role": "Team Member",
    "email": "deviprasaddesalla@gmail.com",
    "phone": "+91 8074844136",
    "certId": "HACK26-039-M2",
    "teamSize": 3
  },
  {
    "id": "part-120",
    "sNo": 120,
    "teamSNo": 40,
    "fullName": "B.Lokesh Manikanta",
    "collegeName": "Ramachandra College of Engineering",
    "teamName": "Tean titans",
    "role": "Team Lead",
    "email": "lokesh13805@gmail.com",
    "phone": "+91 8179585318",
    "certId": "HACK26-040-L",
    "teamSize": 2
  },
  {
    "id": "part-121",
    "sNo": 121,
    "teamSNo": 40,
    "fullName": "B.charan teja",
    "collegeName": "Ramachandra College of Engineering",
    "teamName": "Tean titans",
    "role": "Team Member",
    "email": "charanballemcherry@gmail.com",
    "phone": "+91 9398511033",
    "certId": "HACK26-040-M1",
    "teamSize": 2
  },
  {
    "id": "part-122",
    "sNo": 122,
    "teamSNo": 41,
    "fullName": "Puja sri navya",
    "collegeName": "Godavari Global University",
    "teamName": "Tech forge",
    "role": "Team Lead",
    "email": "pujasrinavya.57@gmail.com",
    "phone": "+91 9701825414",
    "certId": "HACK26-041-L",
    "teamSize": 5
  },
  {
    "id": "part-123",
    "sNo": 123,
    "teamSNo": 41,
    "fullName": "Bhavani",
    "collegeName": "Godavari Global University",
    "teamName": "Tech forge",
    "role": "Team Member",
    "email": "bhavaniambati914@gmail.com",
    "phone": "+91 6309513592",
    "certId": "HACK26-041-M2",
    "teamSize": 5
  },
  {
    "id": "part-124",
    "sNo": 124,
    "teamSNo": 41,
    "fullName": "Sasi bhargavi",
    "collegeName": "Godavari Global University",
    "teamName": "Tech forge",
    "role": "Team Member",
    "email": "sasibhargavi16@gmail.com",
    "phone": "+91 9390974464",
    "certId": "HACK26-041-M3",
    "teamSize": 5
  },
  {
    "id": "part-125",
    "sNo": 125,
    "teamSNo": 41,
    "fullName": "Sri harsha vardhan",
    "collegeName": "Godavari Global University",
    "teamName": "Tech forge",
    "role": "Team Member",
    "email": "sriharshavardhantirumalarowthu@gmail.com",
    "phone": "+91 9390549017",
    "certId": "HACK26-041-M4",
    "teamSize": 5
  },
  {
    "id": "part-126",
    "sNo": 126,
    "teamSNo": 42,
    "fullName": "K.Blessy",
    "collegeName": "GIET Engineering College",
    "teamName": "Tech Titans",
    "role": "Team Lead",
    "email": "kovvuriblessy@gmail.com",
    "phone": "+91 8341381161",
    "certId": "HACK26-042-L",
    "teamSize": 2
  },
  {
    "id": "part-127",
    "sNo": 127,
    "teamSNo": 42,
    "fullName": "P.Dhanusha",
    "collegeName": "GIET Engineering College",
    "teamName": "Tech Titans",
    "role": "Team Member",
    "email": "pillilakshmidhanusha@gmail.com",
    "phone": "+91 7989366936",
    "certId": "HACK26-042-M1",
    "teamSize": 2
  },
  {
    "id": "part-128",
    "sNo": 128,
    "teamSNo": 43,
    "fullName": "Devi Sri Lakshmi priya Lolla",
    "collegeName": "Godavari Global University",
    "teamName": "Techsync",
    "role": "Team Lead",
    "email": "lolladevisrilakshmipriya@gmail.com",
    "phone": "+91 8374666997",
    "certId": "HACK26-043-L",
    "teamSize": 2
  },
  {
    "id": "part-129",
    "sNo": 129,
    "teamSNo": 43,
    "fullName": "Lachireddy meghana",
    "collegeName": "Godavari Global University",
    "teamName": "Techsync",
    "role": "Team Member",
    "email": "meghanalakshmi2007@gmail.com",
    "phone": "+91 9494437368",
    "certId": "HACK26-043-M1",
    "teamSize": 2
  },
  {
    "id": "part-130",
    "sNo": 130,
    "teamSNo": 44,
    "fullName": "Koppolu Srinadh",
    "collegeName": "Godavari Global University",
    "teamName": "Terminal stack",
    "role": "Team Lead",
    "email": "koppolusrinadh0@gmail.com",
    "phone": "+91 7981715399",
    "certId": "HACK26-044-L",
    "teamSize": 4
  },
  {
    "id": "part-131",
    "sNo": 131,
    "teamSNo": 44,
    "fullName": "Mummana Devi Prasad",
    "collegeName": "Godavari Global University",
    "teamName": "Terminal stack",
    "role": "Team Member",
    "email": "mummanadeviprasad456@gmail.com",
    "phone": "+91 7842837179",
    "certId": "HACK26-044-M1",
    "teamSize": 4
  },
  {
    "id": "part-132",
    "sNo": 132,
    "teamSNo": 44,
    "fullName": "Boddeti Dhana Venkata sai",
    "collegeName": "Godavari Global University",
    "teamName": "Terminal stack",
    "role": "Team Member",
    "email": "dvsaiboddeti@gmail.com",
    "phone": "+91 9703719596",
    "certId": "HACK26-044-M2",
    "teamSize": 4
  },
  {
    "id": "part-133",
    "sNo": 133,
    "teamSNo": 44,
    "fullName": "Akkkireddy durga Vamsi Krishna",
    "collegeName": "Godavari Global University",
    "teamName": "Terminal stack",
    "role": "Team Member",
    "email": "adurgavamsikrishna@gmail.com",
    "phone": "+91 8125178985",
    "certId": "HACK26-044-M3",
    "teamSize": 4
  },
  {
    "id": "part-134",
    "sNo": 134,
    "teamSNo": 45,
    "fullName": "Uma Maheshwari",
    "collegeName": "Pragati Engineering College / University",
    "teamName": "Thinktech",
    "role": "Team Lead",
    "email": "umamaheswariyadamareddy@gmail.com",
    "phone": "+91 9603703364",
    "certId": "HACK26-045-L",
    "teamSize": 3
  },
  {
    "id": "part-135",
    "sNo": 135,
    "teamSNo": 45,
    "fullName": "Renuka Yadamareddy",
    "collegeName": "Pragati Engineering College / University",
    "teamName": "Thinktech",
    "role": "Team Member",
    "email": "renukayadamareddy249@gmail.com",
    "phone": "+91 9948779918",
    "certId": "HACK26-045-M2",
    "teamSize": 3
  },
  {
    "id": "part-136",
    "sNo": 136,
    "teamSNo": 46,
    "fullName": "S charan teja",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "VisionX",
    "role": "Team Lead",
    "email": "charantejasarika32@gmail.com",
    "phone": "+91 9550977976",
    "certId": "HACK26-046-L",
    "teamSize": 4
  },
  {
    "id": "part-137",
    "sNo": 137,
    "teamSNo": 46,
    "fullName": "R Lokesh",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "VisionX",
    "role": "Team Member",
    "email": "rajalokesh120@gmail.com",
    "phone": "+91 8096063819",
    "certId": "HACK26-046-M1",
    "teamSize": 4
  },
  {
    "id": "part-138",
    "sNo": 138,
    "teamSNo": 46,
    "fullName": "K Rohith",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "VisionX",
    "role": "Team Member",
    "email": "kattarohith555@gmail.com",
    "phone": "+91 9912503129",
    "certId": "HACK26-046-M2",
    "teamSize": 4
  },
  {
    "id": "part-139",
    "sNo": 139,
    "teamSNo": 46,
    "fullName": "N Jaya sai lakshmi",
    "collegeName": "Sasi Institute of Technology & Engineering",
    "teamName": "VisionX",
    "role": "Team Member",
    "email": "jayasainekkanti@gmail.com",
    "phone": "+91 9676551838",
    "certId": "HACK26-046-M3",
    "teamSize": 4
  },
  {
    "id": "part-140",
    "sNo": 140,
    "teamSNo": 47,
    "fullName": "SAIKIRAN CHAPA",
    "collegeName": "GIET Engineering College",
    "teamName": "WE CAN",
    "role": "Team Lead",
    "email": "gietsaikiran@gmail.com",
    "phone": "+91 8106574159",
    "certId": "HACK26-047-L",
    "teamSize": 2
  }
];
